name = "relax-cats-bot"
main = "bin/src/main.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
dev.port = 8080

[build]
command = "cd .. && make build"
watch_dir = ["../src"]

[[d1_databases]]
binding = "DB"
database_name = "LAST_REQUEST_TIME_D1"
database_id = "93980957-5d8d-4127-a10f-c6353905cdaa"
