name = "relax-cats-bot"
main = "_build/main.js"
compatibility_date = "2023-10-30"
node_compat = false

[build]
command = "clj2js src/main.clj > _build/main.js"
watch_dir = ["src"]

[[d1_databases]]
binding = "DB"
database_name = "LAST_REQUEST_TIME_D1"
database_id = "93980957-5d8d-4127-a10f-c6353905cdaa"
